import { chromium } from 'playwright';
const b=await chromium.launch();
const page=await (await b.newContext()).newPage();
const logs=[];
page.on('console', m=>{ const t=m.text(); if(/error|denied|sync|ws|websock/i.test(t)) logs.push('['+m.type()+'] '+t.slice(0,150)); });
page.on('pageerror', e=>logs.push('PAGEERR '+String(e).slice(0,150)));
await page.goto('http://127.0.0.1:7420/login',{waitUntil:'load'});
await page.waitForSelector('input[name=email]');
await page.fill('input[name=email]','e2e-admin@e2e.test');
await page.fill('input[name=password]','Ol-Fixture-9x7K');
await Promise.all([page.waitForURL('**/hub**',{timeout:30000}), page.click('button[type=submit]')]);
await page.goto('http://127.0.0.1:7420/project/6ab73507941509df73b96a34',{waitUntil:'load'});
await page.waitForSelector('.cm-content',{timeout:45000});
const t0=await page.evaluate(()=>document.querySelector('.cm-content').innerText.length);
console.log('editor open, textlen', t0, 'at', new Date().toISOString());
const { execFileSync } = await import('node:child_process');
execFileSync('node', ['/tmp/wsprj/push.cjs', '6ab73507941509df73b96a34', '% A4MARK-' + Date.now()], { cwd: '/tmp/wsprj', stdio: 'inherit' });
await page.waitForTimeout(7000);
const t1=await page.evaluate(()=>document.querySelector('.cm-content').innerText);
console.log('after push: len', t1.length, 'includes A4MARK:', /A4MARK-/.test(t1));
console.log('--- logs ---');
console.log(logs.slice(-8).join('\n'));
await b.close();
