import { chromium } from 'playwright';
const BASE='http://127.0.0.1:7420';
const username='e2e-admin@e2e.test', password='Ol-Fixture-9x7K';
const pid = process.argv[2];
const b = await chromium.launch(); const page = await b.newPage();
const fails=[]; const errs=[];
page.on('response', r => { if (r.status()>=400) fails.push(r.status()+' '+r.url()); });
page.on('console', m => { if (m.type()==='error') errs.push(m.text().slice(0,200)); });
page.on('pageerror', e => errs.push('PAGEERR '+(e.message||'').slice(0,300)));
await page.goto(BASE+'/login', { waitUntil: 'domcontentloaded' });
await page.fill('input[name=email]', username);
await page.fill('input[name=password]', password);
await page.click('button[type=submit]');
await page.waitForTimeout(3000);
console.log('after login:', page.url());
await page.goto(BASE+'/editor/'+pid, { waitUntil: 'domcontentloaded' });
await page.waitForTimeout(15000);
console.log('URL:', page.url());
console.log('TITLE:', await page.title());
const body = await page.evaluate(() => document.body.innerText.slice(0,300)).catch(e=>String(e));
console.log('BODY:', body.replace(/\n/g,' | '));
console.log('cm-content?', await page.locator('.cm-content').count());
console.log('ide-root children:', await page.evaluate(()=>{const r=document.getElementById('ide-root'); return r? [...r.children].map(c=>c.tagName+'.'+c.className.slice(0,40)).join(',') : 'none';}));
console.log('FAILED REQUESTS:'); for (const f of [...new Set(fails)].slice(0,15)) console.log('  ', f.slice(0,150));
console.log('CONSOLE ERRORS:'); for (const e of [...new Set(errs)].slice(0,15)) console.log('  ', e);
await b.close();
