const BASE = 'http://127.0.0.1:4000'
const b = await (await import('playwright')).chromium.launch({ headless: true })
const page = await (await b.newContext()).newPage()
const fails = [], cons = []
page.on('response', (r) => { if (r.status() >= 400) fails.push(`${r.status()} ${r.request().method()} ${r.url()}`) })
page.on('requestfailed', (r) => fails.push(`FAILED ${r.method()} ${r.url().slice(0,110)} :: ${r.failure()?.errorText}`))
page.on('console', (m) => { if (m.type() === 'error') cons.push(m.text().slice(0, 180)) })
page.on('pageerror', (e) => cons.push('PAGEERR ' + String(e).slice(0, 180)))

await page.goto(BASE + '/login')
await page.fill('input[name="email"]', 'e2e-admin@e2e.test')
await page.fill('input[name="password"]', 'Ol-Fixture-9x7K')
await page.click('button[type="submit"]')
await page.waitForTimeout(6000)
console.log('after login URL:', page.url())
await page.waitForTimeout(8000)
const btn = await page.locator('button:has-text("New project")').count()
console.log('New project button count:', btn)
console.log('body head:', (await page.evaluate(() => document.body.innerText.slice(0, 250))).replace(/\n/g, ' | '))
console.log('\n=== RESPONSE FAILURES ===')
for (const f of fails.slice(0, 25)) console.log(' ', f)
console.log('\n=== CONSOLE ERRORS ===')
for (const c of cons.slice(0, 15)) console.log(' ', c)
await b.close()
