import { chromium } from 'playwright';
const BASE='http://127.0.0.1:7420';
const pid='6ab73507941509df73b96a34';
const b = await chromium.launch();
const page = await b.newPage();
const fails=[]; const errs=[];
page.on('response', r => { if (r.status()>=400) fails.push(r.status()+' '+r.url().slice(0,130)); });
page.on('pageerror', e => errs.push('PAGEERR '+(e.message||'').slice(0,250)));
page.on('console', m => { if (m.type()==='error') errs.push(m.text().slice(0,200)); });
await page.goto(BASE+'/login', { waitUntil: 'domcontentloaded' });
await page.waitForSelector('input[name=email]', { timeout: 15000 }).catch(()=>console.log('NO LOGIN FORM'));
await page.fill('input[name=email]', 'e2e-admin@e2e.test');
await page.fill('input[name=password]', 'Ol-Fixture-9x7K');
await page.click('button[type=submit]');
await page.waitForTimeout(3000);
console.log('after login:', page.url());
console.log('HUB rendered?', await page.evaluate(()=>document.body.innerText.includes('Projects')||document.body.innerText.includes('All projects')));
await page.goto(BASE+'/editor/'+pid, { waitUntil: 'domcontentloaded' });
await page.waitForSelector('.cm-content', { timeout: 45000 }).then(()=>console.log('!!! cm-content VISIBLE — IDE BOOTED !!!')).catch(()=>console.log('cm-content TIMEOUT'));
await page.waitForTimeout(3000);
console.log('cm-content count:', await page.locator('.cm-content').count());
const body = await page.evaluate(()=>document.body.innerText.slice(0,200).replace(/\n/g,' | '));
console.log('BODY:', body);
console.log('FAILED:', [...new Set(fails)].slice(0,8));
console.log('ERRORS:', [...new Set(errs)].slice(0,8));
await b.close();
