package sharejstptwo

// Golden table (50 rows) captured live from the vendored Node oracle of
// app/js/sharejs/types/text-tp2.js. Contract: input = JSON text of the args
// array (null for create); expected = oracle JSON payload, or ERR:<verbatim>.

type goldenRow struct{ kind, name, input, expected string }

var goldenRows = []goldenRow{
	{"create", "create", "null", "{\"charLength\":0,\"totalLength\":0,\"positionCache\":[],\"data\":[]}"},
	{"deserialize", "deserialize-1", "[[\"Hello \",5,\"world\"]]", "{\"charLength\":11,\"totalLength\":16,\"positionCache\":[],\"data\":[\"Hello \",5,\"world\"]}"},
	{"deserialize", "deserialize-empty", "[[]]", "{\"charLength\":0,\"totalLength\":0,\"positionCache\":[],\"data\":[]}"},
	{"serialize", "serialize-1", "[[\"a\",2,\"b\"]]", "[\"a\",2,\"b\"]"},
	{"serialize", "serialize-invalid", "[null]", "ERR:invalid doc snapshot"},
	{"apply", "apply-empty", "[[\"Hello\"],[]]", "{\"charLength\":0,\"totalLength\":0,\"positionCache\":[],\"data\":[]}"},
	{"apply", "apply-skip-all", "[[\"Hello\",3,\"World\"],[11]]", "{\"charLength\":8,\"totalLength\":11,\"positionCache\":[],\"data\":[\"Hello\",3,\"Wor\"]}"},
	{"apply", "apply-ins-str", "[[\"Hello\"],[3,{\"i\":\"X\"},2]]", "{\"charLength\":6,\"totalLength\":6,\"positionCache\":[],\"data\":[\"HelXlo\"]}"},
	{"apply", "apply-ins-tombs", "[[\"Hello\"],[{\"i\":4}]]", "{\"charLength\":0,\"totalLength\":4,\"positionCache\":[],\"data\":[4]}"},
	{"apply", "apply-del", "[[\"Hi\",3,\"World\"],[2,{\"d\":5},2]]", "{\"charLength\":4,\"totalLength\":9,\"positionCache\":[],\"data\":[\"Hi\",5,\"rl\"]}"},
	{"apply", "apply-combo", "[[\"abc\",2,\"def\"],[1,{\"i\":\"Q\"},4,{\"d\":2},{\"i\":1}]]", "{\"charLength\":4,\"totalLength\":9,\"positionCache\":[],\"data\":[\"aQbc\",5]}"},
	{"apply", "apply-past-end", "[[\"Hi\"],[10]]", "ERR:Operation goes past the end of the document"},
	{"apply", "apply-invalid-snapshot", "[null,[]]", "ERR:Snapshot is invalid"},
	{"apply", "checkop-not-array", "[[],{\"i\":1}]", "ERR:Op must be an array of components"},
	{"apply", "checkop-adj-skip", "[[],[1,2]]", "ERR:Adjacent skip components should be combined"},
	{"apply", "checkop-bad-comp", "[[],[\"x\"]]", "ERR:Op components must be objects or numbers"},
	{"apply", "checkop-skip0", "[[],[0]]", "ERR:Skip components must be a positive number"},
	{"apply", "checkop-i-empty", "[[],[{\"i\":\"\"}]]", "ERR:Inserts must insert a string or a +ive number"},
	{"apply", "checkop-no-id", "[[],[{}]]", "ERR:Operation component must define .i or .d"},
	{"apply", "checkop-d-str", "[[],[{\"d\":\"x\"}]]", "ERR:Deletes must be a +ive number"},
	{"apply", "checkop-d0", "[[],[{\"d\":0}]]", "ERR:Deletes must be a +ive number"},
	{"normalize", "norm-basic", "[[1,{\"i\":\"a\"},{\"i\":\"b\"},{\"i\":\"a\"},{\"d\":2},{\"d\":3},2,3,0,{\"i\":\"\"},{\"d\":0},{\"i\":3}]]", "[1,{\"i\":\"aba\"},{\"d\":5},5,{\"i\":3}]"},
	{"normalize", "norm-tombs", "[[{\"i\":2},{\"i\":3}]]", "[{\"i\":5}]"},
	{"appendop", "app-num-num", "[[4],3]", "[7]"},
	{"appendop", "app-i-str", "[[{\"i\":\"a\"}],{\"i\":\"b\"}]", "[{\"i\":\"ab\"}]"},
	{"appendop", "app-i-tomb", "[[{\"i\":2}],{\"i\":3}]", "[{\"i\":5}]"},
	{"appendop", "app-mixtype", "[[{\"i\":\"a\"}],{\"i\":2}]", "[{\"i\":\"a\"},{\"i\":2}]"},
	{"appendop", "app-d-d", "[[{\"i\":\"a\"},{\"d\":1}],{\"d\":4}]", "[{\"i\":\"a\"},{\"d\":5}]"},
	{"appendop", "app-noop0", "[[4],0]", "[4]"},
	{"transform", "r2-ins-ins-L", "[[{\"i\":\"ab\"}],[{\"i\":\"x\"}],\"left\"]", "[{\"i\":\"ab\"},1]"},
	{"transform", "r2-ins-ins-R", "[[{\"i\":\"ab\"}],[{\"i\":\"x\"}],\"right\"]", "[1,{\"i\":\"ab\"}]"},
	{"transform", "r2-skip-then-ins", "[[1,2],[{\"i\":\"a\"},3],\"left\"]", "ERR:Adjacent skip components should be combined"},
	{"transform", "r2-d-over-ins", "[[{\"d\":3}],[{\"i\":\"a\"},3],\"right\"]", "[1,{\"d\":3}]"},
	{"transform", "r2-skip-d-both", "[[{\"i\":\"Q\"},3,{\"d\":2}],[1,{\"i\":\"ab\"},{\"d\":2},1],\"left\"]", "ERR:Remaining fragments in the op: [object Object]"},
	{"transform", "r2-tombs-ins-L", "[[{\"i\":2},3],[{\"i\":\"xy\"}],\"left\"]", "ERR:Remaining fragments in the op: 3"},
	{"transform", "r2-same-ins-L", "[[{\"i\":\"ab\"}],[{\"i\":\"ab\"},1],\"left\"]", "ERR:The op traverses more elements than the document has"},
	{"transform", "r2-same-ins-R", "[[{\"i\":\"ab\"}],[{\"i\":\"ab\"},1],\"right\"]", "ERR:The op traverses more elements than the document has"},
	{"transform", "r2-d-over-d", "[[{\"d\":2},{\"d\":3}],[{\"d\":3},2],\"left\"]", "[{\"d\":5}]"},
	{"transform", "both-skip", "[[5],[5],\"right\"]", "[5]"},
	{"transform", "badside", "[[3],[3],\"bogus\"]", "ERR:side (bogus) should be 'left' or 'right'"},
	{"transform", "empty-other", "[[3,{\"i\":\"x\"}],[],\"left\"]", "ERR:Remaining fragments in the op: 3"},
	{"transform", "empty-op", "[[],[3],\"left\"]", "ERR:The op traverses more elements than the document has"},
	{"prune", "prune-d-over-ins-err", "[[{\"i\":2},{\"d\":1},3],[{\"i\":\"x\"}]]", "ERR:The transformed op deletes locally inserted characters - it cannot be purged of the insert."},
	{"prune", "prune-fragments-err", "[[3],[{\"i\":\"x\"},{\"i\":\"y\"}]]", "ERR:Remaining fragments in the op: 1"},
	{"prune", "prune-d-match", "[[3,{\"d\":2}],[3,{\"d\":2}]]", "[3,{\"d\":2}]"},
	{"compose", "compose-null", "[null,[1,{\"i\":\"x\"}]]", "[1,{\"i\":\"x\"}]"},
	{"compose", "compose-basic", "[[3,{\"i\":\"a\"}],[2,1]]", "ERR:Adjacent skip components should be combined"},
	{"compose", "compose-del-converts", "[[{\"i\":4}],[2,{\"d\":1}]]", "[{\"i\":4}]"},
	{"compose", "compose-fragments-err", "[[3],[]]", "ERR:Remaining fragments in op1: 3"},
	{"compose", "compose-past-err", "[[1],[5]]", "ERR:The op traverses more elements than the document has"},
}
