package otc

import (
	"encoding/json"
	"fmt"
	"os"
	"testing"
)

// Ported from the CLSI service's clsi/ot package (package deleted 2026-09-21
// after go/libraries/otc superseded it — single source of truth). Source
// fixture: /tmp/otto/spfuzz2.json, 80,782 differential fuzz rows generated by
// the Node reference implementation (safepathname.js oracle):
// input → clean() output, clean() reason, isClean(), isClean reason.

type oracleRow struct {
	I   string `json:"i"`
	C   string `json:"c"`
	R   string `json:"r"`
	K   bool   `json:"k"`
	Why string `json:"why"`
}

func loadSpfuzzRows(t *testing.T) []oracleRow {
	data, err := os.ReadFile("testdata/spfuzz2.json")
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	var rows []oracleRow
	if err := json.Unmarshal(data, &rows); err != nil {
		t.Fatalf("unmarshal fixture: %v", err)
	}
	if len(rows) == 0 {
		t.Fatal("no oracle rows")
	}
	return rows
}

func TestSafePathnameOracle(t *testing.T) {
	rows := loadSpfuzzRows(t)

	mismatch := 0
	for idx, row := range rows {
		cleaned, reason := CleanDebug(row.I)
		if cleaned != row.C {
			mismatch++
			if mismatch <= 20 {
				t.Logf("MISMATCH clean row %d: in=%q want=%q got=%q", idx, row.I, row.C, cleaned)
			}
			continue
		}
		if reason != row.R {
			mismatch++
			if mismatch <= 20 {
				t.Logf("MISMATCH reason row %d: in=%q want=%q got=%q", idx, row.I, row.R, reason)
			}
			continue
		}
		ok, why := IsCleanDebug(row.I)
		if ok != row.K || why != row.Why {
			mismatch++
			if mismatch <= 20 {
				t.Logf("MISMATCH isClean row %d: in=%q want=(%v,%q) got=(%v,%q)", idx, row.I, row.K, row.Why, ok, why)
			}
		}
	}
	if mismatch > 0 {
		t.Fatalf("%d/%d mismatches", mismatch, len(rows))
	}
	fmt.Printf("PASS safe_pathname oracle: %d rows\n", len(rows))
}
