// Generated by `yarn cm:gen:themes` (see
// generate-react-codemirror-themes.mjs). The entries map OlliTeX theme
// ids to the bundled CodeMirror-6 CSS custom-property class, and carry
// the dark/light metadata the editor + Mantine theming use.
// Keep in sync by re-running the generator whenever the vendored JSON
// files under this directory change. Do not hand-edit the tables.
import type {} from './abcdef.json'

export interface CM6ThemeEntry {
  cmClass: string
  dark: boolean
  label: string
}

export const CM6_THEME_MAP: Record<string, CM6ThemeEntry> = {
  abcdef: { cmClass: 'tok-abcdef', dark: true, label: 'AbCDEF' },
  abyss: { cmClass: 'tok-abyss', dark: true, label: 'Abyss' },
  androidstudio: { cmClass: 'tok-androidstudio', dark: false, label: 'Android Studio' },
  andromeda: { cmClass: 'tok-andromeda', dark: true, label: 'Andromeda' },
  atomone: { cmClass: 'tok-atomone', dark: true, label: 'Atom One' },
  aura: { cmClass: 'tok-aura', dark: true, label: 'Aura' },
  basic: { cmClass: 'tok-basic', dark: false, label: 'Basic' },
  bbedit: { cmClass: 'tok-bbedit', dark: false, label: 'BBEdit' },
  bespin: { cmClass: 'tok-bespin', dark: true, label: 'Bespin' },
  console: { cmClass: 'tok-console', dark: true, label: 'Console' },
  copilot: { cmClass: 'tok-copilot', dark: false, label: 'GitHub Copilot' },
  darcula: { cmClass: 'tok-darcula', dark: true, label: 'Darcula' },
  duotone: { cmClass: 'tok-duotone', dark: true, label: 'Duotone' },
  frappe: { cmClass: 'tok-frappe', dark: true, label: 'Frappe (GruvBox)' },
  gruvbox: { cmClass: 'tok-gruvbox', dark: true, label: 'GruvBox' },
  kimbie: { cmClass: 'tok-kimbie', dark: true, label: 'Kimbie Dark' },
  material: { cmClass: 'tok-material', dark: true, label: 'Material' },
  monokai: { cmClass: 'tok-monokai', dark: true, label: 'Monokai' },
  'monokai-dimmed': { cmClass: 'tok-monokai-dimmed', dark: true, label: 'Monokai Dimmed' },
  'noctis-lilac': { cmClass: 'tok-noctis-lilac', dark: true, label: 'Noctis Lilac' },
  nord: { cmClass: 'tok-nord', dark: true, label: 'Nord' },
  okaidia: { cmClass: 'tok-okaidia', dark: true, label: 'Okaidia' },
  'one-dark': { cmClass: 'tok-one-dark', dark: true, label: 'One Dark' },
  quietlight: { cmClass: 'tok-quietlight', dark: false, label: 'Quiet Light' },
  red: { cmClass: 'tok-red', dark: true, label: 'Red' },
  'rose-pine': { cmClass: 'tok-rose-pine', dark: true, label: 'Rosé Pine' },
  'rose-pine-dawn': { cmClass: 'tok-rose-pine-dawn', dark: false, label: 'Rosé Pine Dawn' },
  solarized: { cmClass: 'tok-solarized', dark: true, label: 'Solarized Dark' },
  solarizedlight: { cmClass: 'tok-solarizedlight', dark: false, label: 'Solarized Light' },
  sublime: { cmClass: 'tok-sublime', dark: false, label: 'Sublime' },
  'tokyo-night': { cmClass: 'tok-tokyo-night', dark: true, label: 'Tokyo Night' },
  'tokyo-night-day': { cmClass: 'tok-tokyo-night-day', dark: false, label: 'Tokyo Night Day' },
  'tokyo-night-storm': { cmClass: 'tok-tokyo-night-storm', dark: true, label: 'Tokyo Night Storm' },
  'tomorrow-night-blue': { cmClass: 'tok-tomorrow-night-blue', dark: true, label: 'Tomorrow Night Blue' },
  vscode: { cmClass: 'tok-vscode', dark: false, label: 'VS Code' },
  white: { cmClass: 'tok-white', dark: false, label: 'White' },
}
