// OIDF wire layer (S3) — ES256 Compact JWS, RFC 8550 kid, UUID jti.
//
// Oracle: npm @oidfed/core v1.0.0 (FINDINGS distillation; fixtures in
// testdata/ generated by npm v1.0.0 and re-verified byte-for-byte by the
// tests). npm @oidfed/oidc v1.0.0 createClientAssertion (typ: "JWT") is
// the second oracle for the assertion shape.
//
// Compact JWS (RFC 7515 §3.1):
//
//	<base64url(JSON protected header)|.
//	<base64url(JSON payload)>|
//	<base64url(r‖s, 64 bytes)>
//
// signature = base64url(r‖s) over SHA-256(signingInput) — 7518 §3.2 ES256
// (NOT ASN.1 DER); header {alg:"ES256", typ, kid}.
package federation

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"errors"
	"math/big"
)

// Wire constants (03 §2, 02 §2, 03 §3 — oracle: npm leaf.mjs /
// ClientAssertionClient.mjs / verify.mjs).
const (
	LEAF_TTL_SECONDS             = 48 * 3600
	CLIENT_ASSERTION_TTL_SECONDS = 300
	ClockSkewSeconds             = 60
	S2sClientAssertionType       = "urn:ietf:params:oauth:client-assertion-type:jwt"
)

// --- machine-code errors (03 §6 maps over these) ---

var (
	ErrBadSignature = errors.New("federation: bad-signature")
	ErrUnknownKid   = errors.New("federation: unknown-kid")
	ErrBadAssertion = errors.New("federation: bad assertion")
)

var b64url = base64.RawURLEncoding

// --- RFC 8550 §2.1 thumbprint (kid) ---

// KeyThumbprint — BASE64URL(SHA-256(canonical JWK)); EC canonical member
// set {crv,kty,x,y} (names sorted, no whitespace). Oracle: npm v1.0.0 kid.
func KeyThumbprint(pub *JWK) (string, error) {
	if pub.Kty != "EC" || pub.Crv != "P-256" || pub.X == "" || pub.Y == "" {
		return "", Errorf("federation: thumbprint requires kty=EC crv=P-256 x/y, got kty=%s crv=%s", pub.Kty, pub.Crv)
	}
	canon := `{"crv":"` + pub.Crv + `","kty":"` + pub.Kty + `","x":"` + pub.X + `","y":"` + pub.Y + `"}`
	sum := sha256.Sum256([]byte(canon))
	return b64url.EncodeToString(sum[:]), nil
}

// --- generation (npm generateSigningKey 'ES256') ---

func GenerateES256() (pub, priv *JWK, err error) {
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return
	}
	xb := key.PublicKey.X.FillBytes(make([]byte, 32))
	yb := key.PublicKey.Y.FillBytes(make([]byte, 32))
	db := key.D.FillBytes(make([]byte, 32))
	pubOut := JWK{Kty: "EC", Crv: "P-256", X: b64url.EncodeToString(xb), Y: b64url.EncodeToString(yb), Alg: "ES256", Use: "sig"}
	privOut := pubOut
	privOut.D = b64url.EncodeToString(db)
	pub, priv, err = &pubOut, &privOut, nil
	if kid, kerr := KeyThumbprint(pub); kerr == nil {
		pub.Kid = kid
		priv.Kid = kid
	}
	return
}

// --- JWK ↔ P-256 ---

func jwkPublicKey(jwk *JWK) (*ecdsa.PublicKey, error) {
	if jwk.Kty != "EC" || jwk.Crv != "P-256" || jwk.X == "" || jwk.Y == "" {
		return nil, Errorf("federation: JWK must be kty=EC crv=P-256 x/y, got kty=%s crv=%s", jwk.Kty, jwk.Crv)
	}
	xb, err := b64url.DecodeString(jwk.X)
	if err != nil {
		return nil, Errorf("federation: JWK x not b64url: %v", err)
	}
	yb, err := b64url.DecodeString(jwk.Y)
	if err != nil {
		return nil, Errorf("federation: JWK y not b64url: %v", err)
	}
	pub := &ecdsa.PublicKey{Curve: elliptic.P256(), X: new(big.Int).SetBytes(xb), Y: new(big.Int).SetBytes(yb)}
	if !pub.Curve.IsOnCurve(pub.X, pub.Y) {
		return nil, Errorf("federation: JWK (x,y) not on P-256")
	}
	return pub, nil
}

func jwkPrivateKey(jwk *JWK) (*ecdsa.PrivateKey, error) {
	pub, err := jwkPublicKey(jwk)
	if err != nil {
		return nil, err
	}
	if jwk.D == "" {
		return nil, Errorf("federation: JWK missing private scalar (d)")
	}
	db, err := b64url.DecodeString(jwk.D)
	if err != nil {
		return nil, Errorf("federation: JWK d not b64url: %v", err)
	}
	return &ecdsa.PrivateKey{PublicKey: *pub, D: new(big.Int).SetBytes(db)}, nil
}

// --- Compact JWS (RFC 7515 §3.1, 7518 §3.2 ES256) ---

// SignJWT — Compact-Sign; typ per npm oracle:
//   - "entity-statement+jwt" (leaf EC, JwtTyp.EntityStatement)
//   - "JWT" (S2S client assertion, createClientAssertion)
func SignJWT(jwk *JWK, typ string, payload []byte) (string, error) {
	if !jwk.IsPrivateJWK() {
		return "", Errorf("federation: SignJWT requires a private JWK (d)")
	}
	pk, err := jwkPrivateKey(jwk)
	if err != nil {
		return "", err
	}
	header := map[string]any{"alg": "ES256", "typ": typ}
	if jwk.Kid != "" {
		header["kid"] = jwk.Kid
	}
	hdr, err := json.Marshal(header)
	if err != nil {
		return "", err
	}
	headerB64 := b64url.EncodeToString(hdr)
	signingInput := headerB64 + "." + b64url.EncodeToString(payload)
	digest := sha256.Sum256([]byte(signingInput))
	r, s, err := ecdsa.Sign(rand.Reader, pk, digest[:])
	if err != nil {
		return "", err
	}
	// 7518 §3.2: signature = base64url(r‖s), each 32 B big-endian (jose's
	// wire shape, NOT ASN.1 DER).
	sig := make([]byte, 64)
	r.FillBytes(sig[:32])
	s.FillBytes(sig[32:])
	return signingInput + "." + b64url.EncodeToString(sig), nil
}

// VerifyJWT — Compact-Verify ES256 against a pinned public JWK.
// (kid, payload, err); ErrUnknownKid on kid mismatch (03 §6 `unknown-kid`
// path), ErrBadSignature on alg/signature failure.
func VerifyJWT(jwk *JWK, jws string) (kid string, payload []byte, err error) {
	headerB64, payloadB64, sigB64, ok := compactSplit(jws)
	if !ok {
		return "", nil, ErrBadAssertion
	}
	hdrB, err := b64url.DecodeString(headerB64)
	if err != nil {
		return "", nil, ErrBadAssertion
	}
	var hdr struct {
		Alg string `json:"alg"`
		Typ string `json:"typ"`
		Kid string `json:"kid"`
	}
	if err := json.Unmarshal(hdrB, &hdr); err != nil {
		return "", nil, ErrBadAssertion
	}
	if hdr.Alg != "ES256" {
		return "", nil, Errorf("federation: unsupported alg %q (want ES256)", hdr.Alg)
	}
	if jwk.Kid != "" && hdr.Kid != jwk.Kid {
		return hdr.Kid, nil, ErrUnknownKid
	}
	payload, err = b64url.DecodeString(payloadB64)
	if err != nil {
		return "", nil, ErrBadAssertion
	}
	sig, err := b64url.DecodeString(sigB64)
	if err != nil || len(sig) != 64 {
		return "", nil, Errorf("federation: ES256 signature must be r‖s 32||32, got %d bytes", len(sig))
	}
	pub, err := jwkPublicKey(jwk)
	if err != nil {
		return "", nil, err
	}
	digest := sha256.Sum256([]byte(headerB64 + "." + payloadB64))
	if !ecdsaVerify(pub, digest[:], new(big.Int).SetBytes(sig[:32]), new(big.Int).SetBytes(sig[32:])) {
		return hdr.Kid, nil, ErrBadSignature
	}
	return hdr.Kid, payload, nil
}

// UUIDv4
// ParseProtectedHeader — npm decodeProtectedHeader (03 §2 step ②).
func ParseProtectedHeader(jws string) (kid, typ, alg string, ok bool) {
	headerB64, _, _, is := compactSplit(jws)
	if !is {
		return "", "", "", false
	}
	hdrB, err := b64url.DecodeString(headerB64)
	if err != nil {
		return "", "", "", false
	}
	var hdr struct {
		Alg string `json:"alg"`
		Typ string `json:"typ"`
		Kid string `json:"kid"`
	}
	if err := json.Unmarshal(hdrB, &hdr); err != nil {
		return "", "", "", false
	}
	return hdr.Kid, hdr.Typ, hdr.Alg, true
}

func compactSplit(jws string) (header, payload, sig string, ok bool) {
	dot1 := indexByte(jws, '.', 0)
	if dot1 < 0 || dot1 == 0 {
		return "", "", "", false
	}
	dot2 := indexByte(jws, '.', dot1+1)
	if dot2 < 0 {
		return "", "", "", false
	}
	if indexByte(jws, '.', dot2+1) >= 0 {
		return "", "", "", false
	}
	return jws[:dot1], jws[dot1+1 : dot2], jws[dot2+1:], true
}

func indexByte(s string, b byte, start int) int {
	for i := start; i < len(s); i++ {
		if s[i] == b {
			return i
		}
	}
	return -1
}

// --- UUIDv4 (jti, 03 §3); crypto/rand, RFC 4122 §4.4 ---

func ecdsaVerify(pub *ecdsa.PublicKey, digest []byte, r, s *big.Int) bool {
	return ecdsa.Verify(pub, digest, r, s)
}

func UUIDv4() string {
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		return ""
	}
	b[6] = (b[6] & 0x0f) | 0x40
	b[8] = (b[8] & 0x3f) | 0x80
	hexDigits := "0123456789abcdef"
	var out [36]byte
	i := 0
	for j := 0; j < 16; j++ {
		if j == 4 || j == 6 || j == 8 || j == 10 {
			out[i] = '-'
			i++
		}
		out[i] = hexDigits[b[j]>>4]
		i++
		out[i] = hexDigits[b[j]&0x0f]
		i++
	}
	return string(out[:])
}
