// S3 wire-pinning tests (oracle: npm @oidfed/core v1.0.0; fixtures
// testdata/{key.json,ca.txt,leaf.txt} generated by npm v1.0.0).
package federation

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func fixture(t *testing.T, name string) string {
	t.Helper()
	b, err := os.ReadFile(filepath.Join("testdata", name))
	if err != nil {
		t.Fatalf("fixture %s: %v", name, err)
	}
	return strings.TrimRight(string(b), "\n")
}

func keyFromFixture(t *testing.T) (pub, priv *JWK) {
	t.Helper()
	b, err := os.ReadFile(filepath.Join("testdata", "key.json"))
	if err != nil {
		t.Fatalf("fixture key.json: %v", err)
	}
	var raw struct {
		Pub  JWK `json:"pub"`
		Priv JWK `json:"priv"`
	}
	if err := json.Unmarshal(b, &raw); err != nil {
		t.Fatalf("fixture key.json: %v", err)
	}
	return &raw.Pub, &raw.Priv
}

// TestKidThumbprintOracle — kid = RFC 8550 thumbprint (8550 §2.1); Go
// recomputation of the npm fixture kid matches byte-for-byte.
func TestKidThumbprintOracle(t *testing.T) {
	pub, priv := keyFromFixture(t)
	got, err := KeyThumbprint(pub)
	if err != nil {
		t.Fatalf("thumbprint: %v", err)
	}
	if got != pub.Kid {
		t.Fatalf("kid mismatch: Go=%q npm=%q (priv has d=%v)", got, pub.Kid, priv.D != "")
	}
	// Go-generated keys: kid must equal our own thumbprint (self-consistent).
	pub2, priv2, err := GenerateES256()
	if err != nil {
		t.Fatal(err)
	}
	if pub2.Kid == "" || priv2.Kid != pub2.Kid {
		t.Fatalf("generated kid not set: pub=%q priv=%q", pub2.Kid, priv2.Kid)
	}
	if want, _ := KeyThumbprint(pub2); want != pub2.Kid {
		t.Fatalf("generated kid != own thumbprint: %q != %q", pub2.Kid, want)
	}
}

// TestVerifyJWSOracleCA — Go verifies the npm v1.0.0-signed S2S client
// assertion (byte oracle; proves Go r‖s + ES256 + header shape match).
func TestVerifyJWSOracleCA(t *testing.T) {
	pub, _ := keyFromFixture(t)
	ca := fixture(t, "ca.txt")
	kid, payload, err := VerifyJWT(pub, ca)
	if err != nil {
		t.Fatalf("VerifyJWT(npm CA): %v", err)
	}
	if kid != pub.Kid {
		t.Fatalf("kid: Go=%q oracle=%q", kid, pub.Kid)
	}
	var claims struct {
		Iss string `json:"iss"`
		Sub string `json:"sub"`
		Aud string `json:"aud"`
		Jti string `json:"jti"`
		Iat int64  `json:"iat"`
		Exp int64  `json:"exp"`
	}
	if err := json.Unmarshal(payload, &claims); err != nil {
		t.Fatalf("claims: %v", err)
	}
	if !strings.HasPrefix(claims.Iss, "urn:overleaf-federation:client:") {
		t.Fatalf("iss: %q", claims.Iss)
	}
	if claims.Sub != claims.Iss {
		t.Fatalf("sub != iss: %q != %q", claims.Sub, claims.Iss)
	}
	if claims.Jti == "" || claims.Exp-claims.Iat != CLIENT_ASSERTION_TTL_SECONDS {
		t.Fatalf("jti/exp-iat: %q / %d", claims.Jti, claims.Exp-claims.Iat)
	}
	// kid pre-check (03 §6 unknown-kid): a DIFFERENT key must reject.
	pub3, _, err := GenerateES256()
	if err == nil {
		if _, _, err := VerifyJWT(pub3, ca); err != ErrUnknownKid {
			t.Fatalf("foreign key must ErrUnknownKid, got %v", err)
		}
	}
	// tampered payload → bad-signature.
	if _, _, err := VerifyJWT(pub, tamperMiddleSegment(ca)); err == nil {
		t.Fatal("tampered payload must fail the signature check")
	}
}

func tamperMiddleSegment(jws string) string {
	parts := strings.Split(jws, ".")
	last := len(parts[1]) - 1
	flip := parts[1][last]
	if flip == 'A' {
		flip = 'B'
	} else {
		flip = 'A'
	}
	parts[1] = parts[1][:last] + string(flip)
	return strings.Join(parts, ".")
}

// TestSignJWTHeaderShape — the Go Compact-JWS header is exactly
// {alg:"ES256", typ, kid} (npm shape); 3 segments; r‖s = 64 bytes (7518 §3.2).
func TestSignJWTHeaderShape(t *testing.T) {
	_, priv, err := GenerateES256()
	if err != nil {
		t.Fatal(err)
	}
	jws, err := SignJWT(priv, "JWT", []byte(`{"jti":"x"}`))
	if err != nil {
		t.Fatal(err)
	}
	kid, typ, alg, ok := ParseProtectedHeader(jws)
	if !ok {
		t.Fatal("parse header")
	}
	if kid != priv.Kid || typ != "JWT" || alg != "ES256" {
		t.Fatalf("header: kid=%q typ=%q alg=%q", kid, typ, alg)
	}
	if len(strings.Split(jws, ".")) != 3 {
		t.Fatal("compact JWS must have exactly 3 segments")
	}
	parts := strings.Split(jws, ".")
	sig, _ := base64.RawURLEncoding.DecodeString(parts[2])
	if len(sig) != 64 {
		t.Fatalf("ES256 signature must be r‖s 32||32 (64 B), got %d", len(sig))
	}
}

// TestLeafEntityConfigurationRoundTrip — Go-built leaf verifies + 02 §2
// pairwise shape: iss==sub==entityId (portless), exp-iat=48h, jwks.keys
// (1 non-revoked key), openid_provider.issuer = OP issuer (leaf check 16),
// openid_relying_party.client_id = entity id, NO authority_hints.
func TestLeafEntityConfigurationRoundTrip(t *testing.T) {
	pub, priv, err := GenerateES256()
	if err != nil {
		t.Fatal(err)
	}
	store := NewMapStore()
	if err := store.SaveKey(context.Background(), &FederationKey{
		Purpose: "federation", Kid: pub.Kid, PublicKey: pub, PrivateKey: priv,
		State: "active", ExpiresAt: 0, PublishedAt: 0, StateChangedAt: 0,
	}); err != nil {
		t.Fatal(err)
	}
	p := &KeyProvider{Store: store, Site: "https://a.example.org:8443"}
	leaf, err := p.BuildLeafEntityConfiguration(time.Now())
	if err != nil {
		t.Fatalf("build leaf: %v", err)
	}
	kid, payload, err := VerifyJWT(pub, leaf)
	if err != nil {
		t.Fatalf("verify Go-built leaf: %v", err)
	}
	if kid != pub.Kid {
		t.Fatalf("leaf kid: %q", kid)
	}
	var ec struct {
		Iss            string         `json:"iss"`
		Sub            string         `json:"sub"`
		Iat            int64          `json:"iat"`
		Exp            int64          `json:"exp"`
		Jwks           map[string]any `json:"jwks"`
		Metadata       map[string]any `json:"metadata"`
		AuthorityHints []string       `json:"authority_hints"`
		TrustMarks     []any          `json:"trust_marks"`
	}
	if err := json.Unmarshal(payload, &ec); err != nil {
		t.Fatalf("leaf payload: %v", err)
	}
	if ec.Iss != "https://a.example.org" || ec.Sub != ec.Iss {
		t.Fatalf("iss/sub must be the portless entity id: %q / %q", ec.Iss, ec.Sub)
	}
	if ec.Exp-ec.Iat != LEAF_TTL_SECONDS {
		t.Fatalf("exp-iat must be 48h, got %d", ec.Exp-ec.Iat)
	}
	if len(ec.AuthorityHints) != 0 {
		t.Fatalf("pairwise leaf must have NO authority_hints, got %v", ec.AuthorityHints)
	}
	if len(ec.TrustMarks) != 0 {
		t.Fatalf("leaf must not carry trust_marks (02 §2 pairwise)")
	}
	keys, _ := ec.Jwks["keys"].([]any)
	if len(keys) != 1 {
		t.Fatalf("leaf jwks.keys must serve the 1 non-revoked key, got %d", len(keys))
	}
	op, _ := ec.Metadata["openid_provider"].(map[string]any)
	if op == nil {
		t.Fatal("metadata.openid_provider missing")
	}
	if issuer, _ := op["issuer"].(string); issuer != "https://a.example.org/federation/oidc" {
		t.Fatalf("openid_provider.issuer = OP issuer (leaf check 16), got %q", issuer)
	}
	rp, _ := ec.Metadata["openid_relying_party"].(map[string]any)
	if rp == nil {
		t.Fatal("metadata.openid_relying_party missing")
	}
	if cid, _ := rp["client_id"].(string); cid != "https://a.example.org" {
		t.Fatalf("openid_relying_party.client_id = entity id, got %q", cid)
	}
}

// TestClientAssertionRoundTrip — Go-built S2S assertion (typ JWT):
// iss/sub = urn:overleaf-federation:client:<origin>, aud = peer S2S
// endpoint, jti = UUIDv4, exp = iat + 300 (03 §2).
func TestClientAssertionRoundTrip(t *testing.T) {
	pub, priv, err := GenerateES256()
	if err != nil {
		t.Fatal(err)
	}
	jws, err := signClientAssertion(pub, priv, "overleaf.uni-bremen.de", "https://b.example.org/federation/s2s", 1790404922)
	if err != nil {
		t.Fatalf("sign: %v", err)
	}
	_, payload, err := VerifyJWT(pub, jws)
	if err != nil {
		t.Fatalf("verify: %v", err)
	}
	var ca struct {
		Iss string `json:"iss"`
		Sub string `json:"sub"`
		Aud string `json:"aud"`
		Jti string `json:"jti"`
		Iat int64  `json:"iat"`
		Exp int64  `json:"exp"`
	}
	if err := json.Unmarshal(payload, &ca); err != nil {
		t.Fatal(err)
	}
	if ca.Iss != "urn:overleaf-federation:client:overleaf.uni-bremen.de" || ca.Sub != ca.Iss {
		t.Fatalf("iss/sub: %q / %q", ca.Iss, ca.Sub)
	}
	if ca.Aud != "https://b.example.org/federation/s2s" {
		t.Fatalf("aud: %q", ca.Aud)
	}
	if ca.Exp-ca.Iat != CLIENT_ASSERTION_TTL_SECONDS {
		t.Fatalf("exp-iat = 300 s, got %d", ca.Exp-ca.Iat)
	}
	if !isUUIDv4(ca.Jti) {
		t.Fatalf("jti must be UUIDv4: %q", ca.Jti)
	}
	if _, typ, _, ok := ParseProtectedHeader(jws); !ok || typ != "JWT" {
		t.Fatalf("header typ: %q (want JWT)", typ)
	}
}

func isUUIDv4(s string) bool {
	if len(s) != 36 {
		return false
	}
	for i, c := range s {
		if c == '-' {
			if i != 8 && i != 13 && i != 18 && i != 23 {
				return false
			}
			continue
		}
		if !((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F')) {
			return false
		}
	}
	return s[14] == '4'
}
