#!/usr/bin/env python3
"""Capture the Node web service's rendered shell pages as byte-exact Go porting
fixtures (WEB_GO P1 wave, views contract). Run from the overleaf root against a
live Node web service (e2e default http://127.0.0.1:7420).

Outputs into go/services/web/views/{testdata/,pages_data.go}:
  testdata/<name>.html   raw Node render (fixture of record)
  testdata/<name>.skel   same, dynamic values replaced with slots:
                          \\x01CSRF\\x02 — session csrf token (per request)
                          \\x01NONCE\\x02 — page csp nonce (per request)
  pages_data.go         Go constants holding the skeletons.

Slot substitution is value-only (the attribute name/quotes stay in the
skeleton), and the round-trip (skeleton + captured value == raw fixture) is
asserted before writing. Regenerate this file whenever the Node view layer
changes; the e2e gate (web-go flip spec) remains the authority for live parity.
"""
import http.client
import json
import os
import re
import sys

BASE_HOST = sys.argv[1] if len(sys.argv) > 1 else "127.0.0.1"
BASE_PORT = int(sys.argv[2]) if len(sys.argv) > 2 else 7420
E2E_USER = "e2e-user@e2e.test"
E2E_PASS = "Ol-Fixture-3m2Q"


def request(method, path, headers=None, body=None):
    conn = http.client.HTTPConnection(BASE_HOST, BASE_PORT, timeout=20)
    conn.request(method, path, headers=headers or {}, body=body)
    resp = conn.getresponse()
    data = resp.read().decode("utf-8")
    conn.close()
    return resp.status, dict(resp.getheaders()), data


def get_set_cookie(headers):
    return "; ".join(
        f"{k.split('=', 1)[0]}={k.split('=', 1)[1].split(';')[0]}"
        for k in headers.get("Set-Cookie", "").split(", ")
        if "=" in k
    ) if headers.get("Set-Cookie") else ""


def main():
    # 1) anonymous GET /login → session cookie + csrf
    status, headers, login_html = request("GET", "/login")
    assert status == 200, status
    cookie = get_set_cookie(headers)
    csrf = re.search(r'name="ol-csrfToken" content="([^"]+)"', login_html).group(1)

    # 2) POST /login → logged-in session cookie (for the authed shell pages)
    login_cookie = cookie
    s, h, body = request(
        "POST",
        "/login",
        headers={
            "cookie": cookie,
            "content-type": "application/json",
            "x-csrf-token": csrf,
            "accept": "application/json",
        },
        body=json.dumps({"email": E2E_USER, "password": E2E_PASS}),
    )
    assert s in (200, 302), (s, body[:200])
    if "Set-Cookie" in h:
        login_cookie = get_set_cookie(h)
    # allow Node's fire-and-forget session save to land
    import time

    time.sleep(0.8)

    pages = [
        ("loginHTML", "/login", "anonymous", 200),
        ("registerHTML", "/register", login_cookie, 200),
        ("logoutHTML", "/logout", login_cookie, 200),
        ("restrictedHTML", "/restricted", login_cookie, 200),
        ("notFoundHTML", "/zzz-webgo-parity-404", login_cookie, 404),
    ]
    here = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    td = os.path.join(here, "go", "services", "web", "views", "testdata")
    os.makedirs(td, exist_ok=True)

    CS, NO = "\x01CSRF\x02", "\x01NONCE\x02"
    go_consts = []
    for name, path, auth, want_status in pages:
        status, headers, raw = request(
            "GET", path, headers={"cookie": auth} if auth else {}
        )
        assert status == want_status, (name, status, want_status)
        csrf = re.search(r'name="ol-csrfToken" content="([^"]+)"', raw).group(1)
        nonces = sorted(set(re.findall(r'nonce="([^"]+)"', raw)))
        skel = raw.replace('content="%s"' % csrf, 'content="%s"' % CS, 1)
        for n in nonces:
            skel = skel.replace('nonce="%s"' % n, 'nonce="%s"' % NO)
        back = skel.replace(CS, csrf, 1)
        for n in nonces:
            back = back.replace(NO, n)
        assert back == raw, (name, "round-trip broken")
        with open(os.path.join(td, f"{name}.html"), "w") as f:
            f.write(raw)
        with open(os.path.join(td, f"{name}.skel"), "w") as f:
            f.write(skel)
        go_consts.append(f"const {name} = " + json.dumps(skel, ensure_ascii=False))
        print(f"{name}: {len(raw)} bytes, nonces={len(nonces)}")

    hdr = (
        "package views\n\n"
        "// Code generated by tools/webviews-capture.py from the running Node web\n"
        "// service (byte-exact contract). DO NOT EDIT BY HAND — regenerate and\n"
        "// re-run the round-trip + e2e view-parity gate.\n"
        "//\n"
        "// Slots (value-only, inside existing attribute quotes):\n"
        "\t\\u0001CSRF\\u0001 → page csrf token (session; lazily allocated per P0 pin)\n"
        "\t\\u0001NONCE\\u0001 → page csp nonce (random per render)\n"
    )
    with open(
        os.path.join(here, "go", "services", "web", "views", "pages_data.go"), "w"
    ) as f:
        f.write(hdr + "\n".join(go_consts) + "\n")
    print("pages_data.go written")


if __name__ == "__main__":
    main()
